[[alsa]]
arch = "aarch64"
git-tree-sha1 = "e1ab1f655676fa6a9a377cabf4623449ab7ccfce"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "031a500ac06a12b0cb83225baecc96fd41941378c0266488e5efc52071018609"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "b5b46c73ef60627a69ced41ec616a503385fbc92"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "958a461a164eb91957887e9c0b9bfe260a0e648e136118d03083ed34de72c959"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9dbc2e833ef6c8a46b814bab8dd54750afc72c2e"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "da6d4eb3dce2d6974cbca4447be734f0c2ae9f2884a3f6d245c57c2c9b1e14ca"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.armv6l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a343fe089e8566b4d0daa483e9e269f91a26d586"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "09c2c96f5afb007c2c47e7a3e23c7217d5479aad25d81fda59e1d8a549c859d2"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.armv6l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f47447b4f3364b3b5216e06da37a70dc0b49486f"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "ffd2a64781b2bbe5bd0b200ccc3134e85029e858c84abd55090728e16c022e76"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.armv7l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc8a264185ac9a9cac96bb0af6dae032ee6030a4"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "81fc1382e704278b180d3c6906a75d63c19df5d07010b23b49d84df825a14a10"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.armv7l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "03b769067354ab3e93477939ed0fd1f2ac424ad2"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "56c995c2ba64a6a5e606b30c453e339ddc03b45692097e7efe41bc8298b99950"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "62bd8fcca983f27a42f5320256b13b95435f28e7"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "9091f48d2915e056ac9cb7b11299f6dc17491880a6807226edaaaa559df9ecd2"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.i686-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "2dbd5e2c014ad3a0d794432a6abaa6a81fb0431e"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "c72fdcd8f221597346f56de71f9c1f586574ebbb5798fc515968ce23539e11dd"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "4edb4cf557ab8f2b683aa1905a92c95edeacd609"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "d525bda3855b5244cbe5b7cf0f1c762a216d025557f503d09e80c5c9127d485f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "6c77b4c624c12dc4895e268366ba407e294bd688"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "75a5100402fdf6f7c283e0c80d224161e1e117977264858dc6c29ae039cb84cb"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.5+0/alsa.v1.2.5.x86_64-linux-musl.tar.gz"
