[[alsa]]
arch = "aarch64"
git-tree-sha1 = "d7c82d7c589e461310ed99003d587b43aabc2d83"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "4a1c57802cd4f71f40e20745c8904bc76bae0aabba6cb83f72f9fe5329063fb3"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "bcbd0811ffb6844100dad6cb94cf21ef68236f07"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "66fe17b8bf76200d08d3ced4d6eaa191a31f9c3ec5676aba19a62223db06a5ad"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de3fbcd0a1dd5faa1dee14e89fd6fdb1eca29fb6"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "799c0baae740ff347d02d7a857846d118db3640c983a4ff8d0babe3216bd5475"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.armv6l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba554652310d1721fa1ac468541c1cb02c3651f3"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "4b07614aa62bcdd0e49c5bd8cca3f9898e64af247dffea10cfb3d8fffb8a9055"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.armv6l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa682c44397c35c96c5900707b071897d3b67863"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "926c62f98a4b20b77effeb8a468befa994d6f01ad9b888e0d1dc417d60318535"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.armv7l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ed44d6b187d5d6ab28eae8f8a7312026149dbdb"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "344be6dd6cced693a63a74242d3cca869eae1fc26be8103aa90da620936fa536"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.armv7l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "ff14f882012c5cbbc8ac6d4d81e3c4b7d51a78bc"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "a2a40f2bac0a46f5f62c37a5cb0af5b1b1e99e58e4c84151700aa644c5f720b6"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "8d579019f10a3d5ffa4bd7f169a338283c9e7ac0"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "4915054843913ad734fefae82f8b25fe161cc24ae54cfc87e3b85cb3624ac93f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.i686-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "14884998c788a0a275b74fb78652bb20f7aec99b"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "25763114d50f176c93c4602a343e7039c415574e79775dd167266a5db4be6db5"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "riscv64"
git-tree-sha1 = "b8c6a4b16a89efd813c9d6cb31389771425a8ac3"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "f94e530066157b0a04e34db7f50e984f0e08e5bb669eef06a28f16a9bd8f5e4a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.riscv64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "e01887ff1d007e5e71d5faf5a7048ff1ec71641a"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "e179af077e8a835b191961f5348dd0c5c75dc0bc86b08bc43b45f431441b57f5"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "2c3a178c73e3d1fe0acf02fd22e2371be528d0ed"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "95e3ea28fe6efe8970ebc30d39fd34e3abe4d11fbdcf4a1a7d3517d69039752c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.13+0/alsa.v1.2.13.x86_64-linux-musl.tar.gz"
