[[alsa]]
arch = "aarch64"
git-tree-sha1 = "b9e129b9362aa52c5fd88ba0b7d42791c428bcb2"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "1a367932626a346dc0c47dec267a172e1acb2dc3b1ef0af0ec07d854f63d6617"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "53cdb7083405f8a07cb610a556217d6637974b8b"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "1130b259585e67270a758b4b33b57470fe1b9e7460caa4b1a7ae696d44e1ab6f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db79025e42543398df21b23c42207754ac65fe87"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "21db2ce7fb6f2abd2f20b5d10dfd6e330a877dc5ee7d76ca86c9c1b64789e56c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.armv6l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4bf43eecc284606ad13eb8f3a2461cbf378a5151"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "4559dcb25cec3e0c65422e5f63bf23acb2ee26ccdfb49ede1b98153556e5b83a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.armv6l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f70b6ef33bcb3e8b92875e273df46d71c5e98a3"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "fb10f0517a592c6d456b0f89d255b93e9be348481f2522145a945fdf0451efcc"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ee4610fc4d757a9da2ba80fd6348f98f59bfe2c"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "3511235e4e67a797c2802f2df326176a10ac396b302dc03f83d79ebe2b50472a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "825de878c4372ae77cf70acc3252247c9b65666b"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "06852b69bf84e6001a8591ef94108358df7ab1ea72784e7f8a81de84dfcf8eb4"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "be58ecbd99d58d7de08dc50c3051e968d3699423"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "1001567e892f3ea3c4fc95e7e69f01aabac4fcfa22d20b7a6c57d86a60355e95"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.i686-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "4998ce9d95e9e7270410bc5bf49424d35c56a567"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "705b634e61541341b49157757467833e5ac28be40fa8f365ce99d2b2edf9dd6d"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "02ed1d6944753a8133b0eed16b66ee6d5627a273"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "5f2bc604433b248fefdcf297e5722166f0b70ee4cb1fcec059515c55724973c9"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "2773817698de2aba42ddf8ca8e022644298f7c53"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "03aee587f5e52bef2acc00c1ba46492f24d454d5d01a59fea342545f501156ef"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.12+0/alsa.v1.2.12.x86_64-linux-musl.tar.gz"
