[[alsa]]
arch = "aarch64"
git-tree-sha1 = "ba46ec440f0ffaddde64bdecc8967475248ca636"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "6ba502c921590f73b5aac298f125d15e0d95e14bdbc9a917436dc037fc86b3c6"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "b0882e0eec8d28f97f89157ce115a38634654030"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "fe6169784e7d351ed625ae03b4f7e7fb9f76c371204a2581505860fe65dfe879"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0f6994501b0742d582c6110c262da41ef3bbec1e"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "7eab01b4709bb57d5536044e7ac3227d7c27a5b77d136f869da6a7a4ed393ffa"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.armv6l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f41f9e6c2c45b479b41ec3100b35707414da3af"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "10f301cadff44bbc62347af5d743aae63123f97e26d8d16c42713fd9b3363baa"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.armv6l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76eba32988ebc27bb6fecc2d98276f085e8a6438"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "ca53e3b5cf63bfe91af6a8ae0f86bfaf5e8c6ce79ab7f48d51172b40cedd4905"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.armv7l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c928b20cd684d699f4a5307979dd3bb20a33aef9"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "de49834e21bb1956fc5ce7cd44c7ea1deb76733c279d1298ba8ad3276f690dc3"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.armv7l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "7ba015e18ddee11def0cb5ee37cf4f89875e3b54"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "b589c7a0d9bf9fb4cffa8008e53bb9496813aafa79f1d3fad3807252cf27b770"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "0cb5377cfd4990089cb9b9bca51a22e3a69873f2"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "6fc2bc314d5a1094f0819eacc77fe263ddab1c074a83876b8876303eac44b3e1"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.i686-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "9a3f2626327b84c74c11c69c034437b50f7b1c2a"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "c6cd1539c5b412ed47b94f20e0282dfef1e0e9fe4c3958bebf85e0c338f28082"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "riscv64"
git-tree-sha1 = "dedad3aef33596c8327c4e1ef15ac7380aee7453"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "ccb4cd7f81ae8dfc1bf0c05634efe87b1e137d58079845f25e2f88971bc1cf44"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.riscv64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "bc658c17d8e2add3e3134c4b1075d1386cb5418e"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "b6c26bc60082a2667cf306593966637ebfaa69a8cc6397fcd57bb63d5c95bea6"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "e4b296adc9539d5d003d83280f923acd6fc1b0e6"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "55836fc1bfd247755aec2c70a6caa0b79e3f1bda7d33dea6640fe9d9c2b41fdf"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.15+0/alsa.v1.2.15.x86_64-linux-musl.tar.gz"
