[[alsa]]
arch = "aarch64"
git-tree-sha1 = "b8312ac6ec422b347dbb60d8efc2947781581309"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "6bc58a04ffbc08c5138820c33ee8cd5c10f0431e5dce6d8c70436956826514ba"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "87e0860459f85b16277a37cf4d5bace427cba994"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "a5d80b658dd6fec9a56051a3353bc663229b61948a1556f48f5c5d14a066213f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03b5d8bb45ddd9dc7b943ee365ca431c329ee557"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "22dda9f9528e7bb4b3b358267acbd1945df190c8ba66003a3526accdfc14605e"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.armv7l-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3758157108773205df05cf22f497f4c8c2439aa"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "98ddab42783691b5d5bb2eb7ad6623aa5af1fa10845983f7aaed035b742fcbb8"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.armv7l-linux-musleabihf.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "6ad3f3d47d8b56bbbfdfe68ebc594c87d196fd7f"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "d07f6a3b4803876c58c48d11ec8970305befe83e682cfc30a9051dc73149ccaa"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "ad6f85f7cf5c72a6f2deb47a0286d6de8019c880"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "38bd0063ef0bc069c787c9bcba588257e45901c609357d8c7f107f87a2aa38aa"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.i686-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "c533408d83ae2d668a9838393f9d9dfe69223345"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "3a27eaa23ec26a03cbf322896a146ff02eddfb4c71c7ee0a1f1b72fe32ee4317"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "bd483fac1bb38143a3371a70254f3ce93d91119d"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "2fb5dca08ca306703c869abbba2431c8e0286a8ef47153e55f216effd123373b"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "bae013eb6577bdda152c57f11661b3e346639792"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "1b3f355e3c750b59b386239e3880be73e1f9a73d6264ab9cc12e9a05d4d0d741"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.4+0/alsa.v1.2.4.x86_64-linux-musl.tar.gz"
