[[alsa]]
arch = "armv7l"
git-tree-sha1 = "23baf79e4a2d5fd898e39e1adffd2e55e83bc2d4"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "f85ff93ff6cf16a16a0db8293ce58e1d3290c6f5a90881f6ca2cb2119cdcaa28"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.arm-linux-gnueabihf.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "cbfb620fe74d1f6790afc59eb63a68b47788b569"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "53ae4f53873c36c98c3d2a8987b0f06dc9d82efbfaabc020424ec936bae650ab"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.x86_64-linux-gnu.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "a3fe7f94777c51b9b892df00a1bac2948c602767"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "8019390eea43f1d6a6e0e4bef17703e0c9575676659c42c039222492158b1b16"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.aarch64-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "7047e56a428c808fdafdf21d1a5560cdb2a2e02f"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "ff0f57215830604fbf51e3a61a8176d2507bc70c86d4a1ef21667040f2981683"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.i686-linux-musl.tar.gz"
[[alsa]]
arch = "aarch64"
git-tree-sha1 = "60d9b963dd5393c16b0d5922b80ad345c632a798"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "9c9a934e4c97f21446fe08f861f994f14fd7574b95e6b6c3274d37b923c8a55d"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.aarch64-linux-musl.tar.gz"
[[alsa]]
arch = "powerpc64le"
git-tree-sha1 = "77b2277da9b871a58f29584fac3b4b372da7dac1"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "129461ae391c81fa579a8b4e42509638af445c8309ec0f7d96185f4993e6add1"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.powerpc64le-linux-gnu.tar.gz"
[[alsa]]
arch = "i686"
git-tree-sha1 = "194f54a2a0b5a1e5175658760cbb3c87dcf1b9a1"
libc = "glibc"
os = "linux"

    [[alsa.download]]
    sha256 = "7de369a4a60193bd77e0612d70078733cef3378718343f18bc036128734a069a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.i686-linux-gnu.tar.gz"
[[alsa]]
arch = "x86_64"
git-tree-sha1 = "8c9733dcb5367fc3361995a33fce00fbc2793b8f"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "bae98bbda973c5671d8894231b5334cb5b54fbac79b4f4f6f7fe0f3ad55d4846"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.x86_64-linux-musl.tar.gz"
[[alsa]]
arch = "armv7l"
git-tree-sha1 = "e6853a012ad04a73557971f6fbae4492b1669d5b"
libc = "musl"
os = "linux"

    [[alsa.download]]
    sha256 = "aeeae492c3b575b95308813850c797678cb674b9fcd4817f9e15fd4f3c7ddeda"
    url = "https://github.com/JuliaBinaryWrappers/alsa_jll.jl/releases/download/alsa-v1.2.1-1+0/alsa.v1.2.1-1.arm-linux-musleabihf.tar.gz"
